name: publish-beta

on:
  push:
    tags: ['v*']

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: |
          sudo apt-get update
          sudo apt-get install -y libxrandr-dev libxtst-dev
      - run: yarn apply-libuiohook-patch
      - name: NPM config
        run: |
          npm config set //registry-lpm.listenai.com/:_password ${{ secrets.LPM_ZHUOBIN_TOKEN }}
          npm config set //registry-lpm.listenai.com/:username zbzhao
          npm config set //registry-lpm.listenai.com/:email zbzhao@listenai.com
      - run: npm install
      - run: npm run build-ts
      # - run: npm publish --tag=beta --registry=https://registry-lpm.listenai.com
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: 'beta'