name: publish-latest

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: NPM config
        run: |
          npm config set //registry-lpm.listenai.com/:_password ${{ secrets.LPM_ZHUOBIN_TOKEN }}
          npm config set //registry-lpm.listenai.com/:username zbzhao
          npm config set //registry-lpm.listenai.com/:email zbzhao@listenai.com
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - uses: battila7/get-version-action@v2
        id: get_version
      - run: npm dist-tag add @listenai/uiohook-napi@${{ steps.get_version.outputs.version-without-v }} latest
      - run: npm dist-tag add @listenai/uiohook-napi@${{ steps.get_version.outputs.version-without-v }} latest --registry=https://registry-lpm.listenai.com



